using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Threading.Tasks;
using GameKit;
using UnityEngine;
using UnityEngine.Scripting;
using LevelPlayImpressionData = Unity.Services.LevelPlay.LevelPlayImpressionData;

namespace Snapline.Services
{
    /// <summary>
    /// Google Analytics for Firebase, behind the kit's <see cref="IAnalyticsService"/>.
    ///
    /// Copied from Sparkwick, which proved the pattern. Written against the NATIVE Android library
    /// through JNI rather than the Firebase Unity SDK, and either of two reasons would settle that on
    /// its own:
    ///
    ///   * The Unity SDK brings its own External Dependency Manager, and this project already has one
    ///     in Assets/ExternalDependencyManager. Two resolvers built from the same assemblies do not
    ///     coexist in one project.
    ///   * It is hundreds of megabytes of editor libraries for what is, here, one class and five calls.
    ///
    /// The Google services Gradle plugin's only job for Analytics is turning google-services.json into
    /// string resources. Plugins/Android/FirebaseConfig.androidlib carries exactly those, generated by
    /// Tools/FirebaseConfig/generate.py, and Firebase starts itself from them when the app launches.
    /// That same manifest starts collection and every consent type switched OFF; the kit switches them
    /// on through <see cref="CollectionEnabled"/> once consent allows.
    ///
    /// It registers alongside Meta and TikTok rather than replacing them; GameKit composes every
    /// analytics adapter. Every Java signature used here was read off the 23.2.0 artifact with javap
    /// (on Sparkwick), not taken from a doc.
    /// </summary>
    [Preserve]
    public sealed class FirebaseAnalyticsService : IAnalyticsService
    {
        private const string Tag = "[Snapline] Firebase";

        private readonly AndroidJavaObject _analytics;
        private bool _collectionEnabled = true;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void Register()
        {
            GameKitProviders.RegisterAnalytics(CreateAsync);
        }

        private static Task<IAnalyticsService> CreateAsync(GameKitConfig config)
        {
            // A real device only. An editor or desktop session has no install behind it, and reporting
            // one would put phantom players into the numbers.
            if (Application.platform != RuntimePlatform.Android)
                return Task.FromResult<IAnalyticsService>(null);

            try
            {
                using (var player = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
                using (var activity = player.GetStatic<AndroidJavaObject>("currentActivity"))
                using (var context = activity.Call<AndroidJavaObject>("getApplicationContext"))
                {
                    // Without the generated resources Firebase starts and reports to nobody, silently.
                    // Checking for them turns that into one clear line in logcat.
                    if (!HasConfig(context))
                    {
                        Debug.LogWarning(Tag + ": google_app_id is not in the app's resources, so " +
                                         "FirebaseConfig.androidlib did not reach the build. Analytics is off.");
                        return Task.FromResult<IAnalyticsService>(null);
                    }

                    AndroidJavaObject instance;
                    using (var type = new AndroidJavaClass("com.google.firebase.analytics.FirebaseAnalytics"))
                        instance = type.CallStatic<AndroidJavaObject>("getInstance", context);

                    var service = new FirebaseAnalyticsService(instance);
                    service.ListenForAdRevenue();
                    Debug.Log(Tag + " Analytics ready.");
                    return Task.FromResult<IAnalyticsService>(service);
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning(Tag + " Analytics could not start: " + e.Message);
                return Task.FromResult<IAnalyticsService>(null);
            }
        }

        private FirebaseAnalyticsService(AndroidJavaObject analytics)
        {
            _analytics = analytics;
        }

        public bool IsAvailable => _analytics != null;

        /// <summary>
        /// Driven by the consent answer. Switches collection off entirely AND tells Google's consent
        /// mode the same thing, because the two are separate settings and a player who refused is
        /// owed both: no events, and no advertising id attached to anything already queued.
        /// </summary>
        public bool CollectionEnabled
        {
            get => _collectionEnabled;
            set
            {
                _collectionEnabled = value;
                if (_analytics == null) return;
                try
                {
                    _analytics.Call("setAnalyticsCollectionEnabled", value);
                    ApplyConsent(value);
                }
                catch (Exception e)
                {
                    Debug.LogWarning(Tag + " could not apply collection=" + value + ": " + e.Message);
                }
            }
        }

        private void ApplyConsent(bool granted)
        {
            using (var types = new AndroidJavaClass("com.google.firebase.analytics.FirebaseAnalytics$ConsentType"))
            using (var statuses = new AndroidJavaClass("com.google.firebase.analytics.FirebaseAnalytics$ConsentStatus"))
            using (var status = statuses.GetStatic<AndroidJavaObject>(granted ? "GRANTED" : "DENIED"))
            using (var map = new AndroidJavaObject("java.util.HashMap"))
            {
                foreach (string type in new[] { "AD_STORAGE", "ANALYTICS_STORAGE", "AD_USER_DATA", "AD_PERSONALIZATION" })
                {
                    using (var key = types.GetStatic<AndroidJavaObject>(type))
                    using (map.Call<AndroidJavaObject>("put", key, status)) { }
                }
                _analytics.Call("setConsent", map);
            }
        }

        // ---- events ---------------------------------------------------------------------------------

        public void LogEvent(string name) => Send(name, null, null);

        public void LogEvent(string name, double value) => Send(name, value, null);

        public void LogEvent(string name, double value, IReadOnlyDictionary<string, object> parameters) =>
            Send(name, value, parameters);

        public void LogPurchase(decimal amount, string currency)
        {
            var parameters = new Dictionary<string, object> { { "currency", currency } };
            Send("purchase", (double)amount, parameters);
        }

        /// <summary>Nothing to do: Firebase counts sessions itself, from the activity lifecycle.</summary>
        public void ResumeSession() { }

        private void Send(string name, double? value, IReadOnlyDictionary<string, object> parameters)
        {
            if (!_collectionEnabled || _analytics == null || string.IsNullOrEmpty(name)) return;
            try
            {
                using (var bundle = new AndroidJavaObject("android.os.Bundle"))
                {
                    string eventName = Translate(name, value, parameters, bundle);
                    if (parameters != null)
                        foreach (KeyValuePair<string, object> p in parameters) Put(bundle, Key(p.Key), p.Value);
                    _analytics.Call("logEvent", eventName, bundle);
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning(Tag + " event '" + name + "' was not sent: " + e.Message);
            }
        }

        /// <summary>
        /// The kit's event names onto Google's RECOMMENDED game events.
        ///
        /// The same reason the Meta adapter maps onto Meta's standard events: Analytics builds its game
        /// reports - level funnels, progression, currency sinks - from these names and these parameters.
        /// The identical data under a custom name is just a counter.
        /// </summary>
        private static string Translate(string name, double? value, IReadOnlyDictionary<string, object> parameters,
                                        AndroidJavaObject bundle)
        {
            switch (name)
            {
                case GameEvents.LevelCompleted:
                    bundle.Call("putLong", "success", 1L);
                    if (value.HasValue) bundle.Call("putLong", "levels_cleared", (long)value.Value);
                    PutLevelName(bundle, parameters);
                    return "level_end";

                case "level_failed":
                    bundle.Call("putLong", "success", 0L);
                    PutLevelName(bundle, parameters);
                    return "level_end";

                case GameEvents.TutorialCompleted:
                    return "tutorial_complete";

                case GameEvents.AchievementUnlocked:
                    bundle.Call("putString", "achievement_id",
                                "levels_" + (value.HasValue ? ((long)value.Value).ToString(CultureInfo.InvariantCulture) : "0"));
                    return "unlock_achievement";

                case GameEvents.SpentCredits:
                    bundle.Call("putString", "virtual_currency_name", "coins");
                    if (value.HasValue) bundle.Call("putDouble", "value", value.Value);
                    if (parameters != null && parameters.TryGetValue("sink", out object sink) && sink != null)
                        bundle.Call("putString", "item_name", Clip(sink.ToString()));
                    return "spend_virtual_currency";

                default:
                    if (value.HasValue) bundle.Call("putDouble", "value", value.Value);
                    return Key(name);
            }
        }

        private static void PutLevelName(AndroidJavaObject bundle, IReadOnlyDictionary<string, object> parameters)
        {
            if (parameters != null && parameters.TryGetValue("level", out object level) && level != null)
                bundle.Call("putString", "level_name", "level_" + Convert.ToString(level, CultureInfo.InvariantCulture));
        }

        private static void Put(AndroidJavaObject bundle, string key, object value)
        {
            switch (value)
            {
                case null: return;
                case string s: bundle.Call("putString", key, Clip(s)); return;
                case bool b: bundle.Call("putLong", key, b ? 1L : 0L); return;
                case int i: bundle.Call("putLong", key, (long)i); return;
                case long l: bundle.Call("putLong", key, l); return;
                case float f: bundle.Call("putDouble", key, (double)f); return;
                case double d: bundle.Call("putDouble", key, d); return;
                case decimal m: bundle.Call("putDouble", key, (double)m); return;
                default: bundle.Call("putString", key, Clip(Convert.ToString(value, CultureInfo.InvariantCulture))); return;
            }
        }

        /// <summary>Analytics drops string values over 100 characters rather than trimming them.</summary>
        private static string Clip(string s) => s.Length <= 100 ? s : s.Substring(0, 100);

        /// <summary>Event and parameter names: letters, digits and underscores, starting with a letter, at most 40.</summary>
        private static string Key(string raw)
        {
            var sb = new StringBuilder(raw.Length + 1);
            foreach (char c in raw.ToLowerInvariant())
                sb.Append((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_' ? c : '_');
            if (sb.Length == 0 || sb[0] < 'a' || sb[0] > 'z') sb.Insert(0, 'e');
            return sb.Length <= 40 ? sb.ToString() : sb.ToString(0, 40);
        }

        // ---- ad revenue -----------------------------------------------------------------------------

        /// <summary>
        /// Every ad LevelPlay shows, with what it earned, as Google's <c>ad_impression</c> event.
        ///
        /// This is what turns Analytics from a player counter into a revenue report: lifetime value per
        /// player, per country, per level reached, and the signal Google Ads needs to buy players who
        /// are worth something. Currency and value are both required or Google Ads ignores the event;
        /// LevelPlay reports revenue in US dollars.
        /// </summary>
        private void ListenForAdRevenue()
        {
            // Raised by the kit's LevelPlay adapter for every ad it shows, from each ad object's own
            // impression event and already on Unity's thread - the replacement for LevelPlay's obsolete
            // global event.
            GameKit.Ads.LevelPlay.LevelPlayService.ImpressionDataReady += LogAdImpression;
        }

        private void LogAdImpression(LevelPlayImpressionData data)
        {
            if (data == null || !_collectionEnabled || _analytics == null) return;
            try
            {
                using (var bundle = new AndroidJavaObject("android.os.Bundle"))
                {
                    bundle.Call("putString", "ad_platform", "LevelPlay");
                    bundle.Call("putString", "ad_source", data.AdNetwork ?? "unknown");
                    bundle.Call("putString", "ad_format", data.AdFormat ?? "unknown");
                    bundle.Call("putString", "ad_unit_name", data.MediationAdUnitName ?? data.InstanceName ?? "unknown");
                    bundle.Call("putString", "currency", "USD");
                    bundle.Call("putDouble", "value", data.Revenue ?? 0d);
                    _analytics.Call("logEvent", "ad_impression", bundle);
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning(Tag + " ad_impression was not sent: " + e.Message);
            }
        }

        private static bool HasConfig(AndroidJavaObject context)
        {
            using (var resources = context.Call<AndroidJavaObject>("getResources"))
            {
                string package = context.Call<string>("getPackageName");
                return resources.Call<int>("getIdentifier", "google_app_id", "string", package) != 0;
            }
        }
    }
}
