"""
Generates Assets/Plugins/Android/FirebaseConfig.androidlib from Config/google-services.json.

This is the whole of what the Google services Gradle plugin does for Analytics: read the JSON and
write it out as Android string resources, which Firebase reads at launch to start itself. Snapline
does it here rather than in Gradle (copied from Sparkwick), so the values sit in the project where
they can be reviewed and no plugin has to be grafted onto Unity's generated build. Re-run after
downloading a new JSON:

    "C:/Program Files/Blender Foundation/Blender 4.2/4.2/python/bin/python.exe" Tools/FirebaseConfig/generate.py

The manifest also switches Analytics collection and all four consent types OFF by default. Firebase
starts recording from its own content provider at process start, before any consent form has been
shown; the service turns collection and setConsent on together once consent allows. Keys verified
in play-services-measurement-impl 23.2.0 (see PLAYBOOK, "Google Analytics for Firebase").
"""
import json
import os
import sys
from xml.sax.saxutils import escape

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE = os.path.join(ROOT, "Config", "google-services.json")
PACKAGE = "com.sciboxstudios.snapline"
LIBRARY = os.path.join(ROOT, "Assets", "Plugins", "Android", "FirebaseConfig.androidlib")

# Off until consent says otherwise. Every one of these must stay "false" here.
CONSENT_DEFAULTS = [
    "firebase_analytics_collection_enabled",
    "google_analytics_default_allow_analytics_storage",
    "google_analytics_default_allow_ad_storage",
    "google_analytics_default_allow_ad_user_data",
    "google_analytics_default_allow_ad_personalization_signals",
]


def main():
    with open(SOURCE, encoding="utf-8") as f:
        data = json.load(f)

    project = data["project_info"]
    clients = [c for c in data.get("client", [])
               if c["client_info"]["android_client_info"]["package_name"] == PACKAGE]
    if not clients:
        sys.exit("google-services.json has no Android app registered as " + PACKAGE +
                 " - it was downloaded for a different app.")
    client = clients[0]

    values = {
        "google_app_id": client["client_info"]["mobilesdk_app_id"],
        "gcm_defaultSenderId": project["project_number"],
        "project_id": project["project_id"],
    }
    keys = client.get("api_key") or []
    if keys:
        values["google_api_key"] = keys[0]["current_key"]
        values["google_crash_reporting_api_key"] = keys[0]["current_key"]
    if project.get("storage_bucket"):
        values["google_storage_bucket"] = project["storage_bucket"]
    web = [o for o in client.get("oauth_client", []) if o.get("client_type") == 3]
    if web:
        values["default_web_client_id"] = web[0]["client_id"]

    os.makedirs(os.path.join(LIBRARY, "res", "values"), exist_ok=True)

    meta = "".join('    <meta-data android:name="%s" android:value="false" />\n' % k for k in CONSENT_DEFAULTS)
    with open(os.path.join(LIBRARY, "AndroidManifest.xml"), "w", encoding="utf-8", newline="\n") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                '<!-- Generated by Tools/FirebaseConfig/generate.py. Resources, plus Analytics OFF until consent. -->\n'
                '<manifest xmlns:android="http://schemas.android.com/apk/res/android"\n'
                '          package="com.sciboxstudios.snapline.firebaseconfig">\n'
                '  <application>\n' + meta +
                '  </application>\n'
                '</manifest>\n')

    with open(os.path.join(LIBRARY, "project.properties"), "w", encoding="utf-8", newline="\n") as f:
        f.write("android.library=true\n")

    keep = ",".join("@string/" + k for k in sorted(values))
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- Generated by Tools/FirebaseConfig/generate.py from Config/google-services.json. -->',
             '<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="%s">' % keep]
    for name in sorted(values):
        lines.append('  <string name="%s" translatable="false">%s</string>' % (name, escape(str(values[name]))))
    lines.append('</resources>')
    with open(os.path.join(LIBRARY, "res", "values", "google-services.xml"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print("Firebase config for %s written: %s; consent defaults off: %d"
          % (PACKAGE, ", ".join(sorted(values)), len(CONSENT_DEFAULTS)))


if __name__ == "__main__":
    main()
